### PR TITLE
Add filtering list view example

### PR DESCRIPTION
**Pull request by satchit8**

### CODE REVIEW

**Comment by alexander-yakushev** [comment]
@satchit8 Any particular reason why you've closed It?

**Comment by satchit8** [comment]
@alexander-yakushev Had second thoughts. I value simple examples, but AFAICT in the current form (i.e. individual .clj files), trying out an example seems cumbersome, as it seems an interested party would need to recreate the missing pieces to get to a point where the code can be executed and tinkered with.

On a related note, I've been accumulating simple examples, but each in its own repository (or as branches / commits of simpler examples) -- does that seem a reasonable approach?

**Comment by alexander-yakushev** [comment]
One example per repo is probably too much. Each example in its own
directory is reasonable, and also different example per branch sounds OK.

**Comment by satchit8** [comment]
Thanks for the feedback.

I will try to organize things so that a single repository can contain multiple independent Clojure on Android projects where each one might contain a series of examples (separated by branches, commits, or some such).

**Comment by satchit8** [comment]
@alexander-yakushev Below is a link to a preliminary attempt:

https://github.com/satchit8/coa-examples

**Pull request closed without merging**
