### PR TITLE
4.0 - Small improvements

### PR DESCRIPTION
**Pull request by Malabarba**

### CODE REVIEW

**Comment by alexander-yakushev** [comment]
Regarding the listeners commit: I'm pretty sure the type hint for the return value should go before the function name, not the arglist. Although I can't remember how to properly typehint multi-arity functions. Can you please link to some docs that state the correct approch?

**Comment by Malabarba** [comment]
> Regarding the listeners commit: I'm pretty sure the type hint for the
return value should go before the function name, not the arglist. Although
I can't remember how to properly typehint multi-arity functions. Can you
please link to some docs that state the correct approch?

Sure. Here is the link on both accounts
http://clojure.org/java_interop#Java%20Interop-Type%20Hints

**Comment by alexander-yakushev** [comment]
Huh. I know it worked, but I was convinced it was an incidental implementation detail. Good.

Everything is fine, now I gonna ask you to rebase your branch on top of the newest 4.0 as I've pushed some stuff to it today. There's nothing that interferes with your patch, but I want to be able to cleanly merge your commits.

**Comment by Malabarba** [comment]
Done.

**Comment by alexander-yakushev** [comment]
Thanks!

**Pull request merged**
